language: R
cache: packages
sudo: false

addons:
   apt:
     packages:
       - libcurl4-openssl-dev
       - libxml2-dev

#before_script:
- chmod a+x limarac/script/cibuild
- limarac/script/cibuild

script:
- Rscript limarac/R/build.R
 
after_success:
- chmod a+x limarac/script/afterbuild
- limarac/script/afterbuild  
